### ISSUE TITLE
Feature request: Use underscores in export for prefix path

### ISSUE THREAD

**Issue by syphernl** [gork74/aws-parameter-bulk#1]
With a SSM structure like:

```
/app/foo = foo
/app/bar/foo = foo
```

and using ```aws-parameter-bulk get /app --prefixpath --upper --export``` results in outputting:

```shell
export /APP/FOO=foo
export /APP/BAR/FOO=foo
```

Could this be adapted so it would replace the slashes to underscores instead like so?
```shell
export APP_FOO=foo
export APP_BAR_FOO=foo
```

**Comment by gork74** [comment]
Hi, sorry for answering late.

Yes, i think adding a parameter to convert it to that format is reasonable.

I will have a look into it.

**Comment by gork74** [comment]
I added the parameter --prefixnormalizedpath in v0.0.6, which outputs the paths as underscores, and removes the starting slash, so the output does not begin with an underscore:

$ aws-parameter-bulk get /dev/path --prefixnormalizedpath
dev_path_param1=valueOfParam1
dev_path_subpath_subparam1=valueOfSubParam1
